name: scanf
description: "A scanf-like scanner as an alternative to regular expressions."
version: 1.1.1
homepage: https://github.com/UlfBierkaemper/dart_scanf

environment:
  sdk: ^3.5.2

dependencies:

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
